// export const GET_VIDEOS_FROM_REMOTE_API = "GET_ALL_VIDEOS";
// export const GET_LIVE_STREAMS_FROM_REMOTE_API = "GET_ALL_LIVE_STREAMS";
export const UI_START_LOADING = "UI_START_LOADING";
export const UI_STOP_LOADING = "UI_STOP_LOADING";